### ISSUE TITLE
Update name of Main branch

### ISSUE THREAD

**Issue by SHAESEN2** [RConsortium/submissions-pilot3-utilities#3]
Can we please update the branch name from 'Master' to 'Main' for obvious reasons?
It should be easy to do so
https://dev.to/darkmavis1980/how-to-rename-the-master-branch-to-main-3ad5

**Comment by laxamanaj** [comment]
Thanks for noting this, @SHAESEN2 .
@bms63 do you mind taking this on?

**Comment by bms63** [comment]
Happy to do this - but you need to make me an admin so I can change `main` to the default branch

**Comment by laxamanaj** [comment]
Thanks, @bms63 .  You're admin now.

**Comment by bms63** [comment]
master removed and main is now the default branch
