### ISSUE TITLE
R-CMD-check

### ISSUE THREAD

**Issue by SHAESEN2** [RConsortium/submissions-pilot3-utilities#4]
Should this be included?

**Comment by laxamanaj** [comment]
@bms63 has a bit more experience on this than me. 

Hi Ben, thoughts on removing this check?

**Comment by bms63** [comment]
I think it is nice to have a Check/Action that the package builds successfully.

**Comment by laxamanaj** [comment]
Upon further reading, I agree. For my own knowledge I googled this a bit more and to reference what it does : https://r-pkgs.org/R-CMD-check.html it's a good to check to run before we share any enhancements to `main` allowing installation of package to the public, generally speaking for any package.

I'll close this as it's good to keep for our pilot 3 package.
